use crate::debug::DebugLevel;
use crate::device_and_device_manager::WithDeviceClassification;
use crate::schemas_cfg::*;
use crate::schemas_control_matcher::ControlMatchers;
use crate::schemas_hid::{HidControlMatcherCfg, HidDeviceCfg};
use crate::schemas_mapping::Mapping;
#[cfg(feature = "midi")]
use crate::schemas_midi::{MidiControlMatcherCfg, MidiMatcherCfg};
use crate::schemas_predefined::ControlsPredefinedCfg;
use crate::schemas_transform::*;

use crate::schemas_value::{AutoOrManual, DeviceControlMatcherRef, DynValueRefs, WithNumInterval, WithRelativity};
use anyhow::{Context, Result, bail};
use chrono::Utc;

use std::fs;
use std::path::{Path, PathBuf};
use std::sync::LazyLock;
use traversable::TraversableMut;
// use yaml_merge_keys::merge_keys_serde;

#[cfg(feature = "more_debug")]
pub const MORE_DEBUG: bool = true;
#[cfg(not(feature = "more_debug"))]
pub const MORE_DEBUG: bool = false;

pub const APP_VERSION_STR: &str = env!("CARGO_PKG_VERSION");
pub const CONFIG_VERSION_STR: &str = APP_VERSION_STR;
pub const APP_DEFAULT_CONFIG_FILE: &str = "conf/default.yaml";
pub const APP_DEFAULT_PREDEF_CONFIG_FILE_CFG_RELATIVE: &str = "predefined.yaml";
pub const APP_CONFIG_SCHEMA_FILE_CFG_RELATIVE: &str = "scheme.json";
pub const APP_AUTHORS: &str = env!("CARGO_PKG_AUTHORS"); // .. and small furry creatures from Alpha Centauri.
pub const APP_NAME: &str = env!("CARGO_PKG_NAME");
pub const APP_COMMAND_NAME: &str = "mmvj";
pub const APP_LONG_NAME: &str = "MMVJ: HID/MIDI transforming I/O mapper and force-feedback-enabled virtual HID manager";
pub const APP_ABOUT: &str = env!("CARGO_PKG_DESCRIPTION");
pub const APP_LONG_ABOUT: &str = APP_ABOUT;
pub const APP_DEFAULT_NO_HOT_RELOAD: &str = "false";
pub const APP_DEFAULT_LATENCY_STR: &str = "normal";
#[cfg(debug_assertions)]
pub const APP_DEFAULT_MAX_LOG_LEVEL: &str = "warn";
#[cfg(not(debug_assertions))]
pub const APP_DEFAULT_MAX_LOG_LEVEL: &str = "error";
pub const MIN_BASE_FREQ_HZ: u32 = 10;
pub const MAX_BASE_FREQ_HZ: u32 = 1000;

#[cfg(not(feature = "gui"))]
pub const GUI_ENABLED_CONST: bool = false;
#[cfg(feature = "gui")]
pub const GUI_ENABLED_CONST: bool = true;

#[cfg(not(feature = "midi"))]
pub const MIDI_ENABLED_CONST: bool = false;
#[cfg(feature = "midi")]
pub const MIDI_ENABLED_CONST: bool = true;

//-----------------------------------------------------------------
pub(crate) trait WithSelfSanitize {
    fn sanitize_inplace(&mut self);
    #[allow(unused)]
    fn sanitize_self(mut self) -> Self
    where
        Self: Sized,
    {
        self.sanitize_inplace();
        self
    }
}

impl Config {
    fn new(cfg_file: PathBuf) -> Self {
        Self {
            cfg_file,
            ..Default::default()
        }
    }

    pub(crate) fn get_yaml_str(&self) -> String {
        let mut yaml = format!(
            "# {APP_NAME} configuration.\n\
             # {APP_NAME} version: {CONFIG_VERSION_STR}\n\
             # Autogenerated at: {}\n\n",
            Utc::now()
        );
        yaml += serde_saphyr::to_string(self)
            .expect("Failed to serialize config.")
            .as_str();
        yaml
    }

    pub(crate) fn recompute_mappings_metadata(&mut self) {
        for mapping in self.mappings.iter_mut() {
            mapping
                .transformation
                .recompute_metadata(AutoOrManual::Auto(crate::schemas_value::InputValueMetadata {
                    relativity: mapping.src.get_relativity(),
                    interval: mapping.src.get_interval(),
                }));
        }
    }

    pub(crate) fn _device_matcher_exists_and_is_enabled(&self, device_matcher_key: &str) -> Option<bool> {
        // TODO: common iface for device matcher on config level.
        self.devices
            .hid
            .get(device_matcher_key)
            .map(|device_matcher| device_matcher.is_enabled())
            .or_else(|| {
                #[cfg(feature = "midi")]
                return self
                    .devices
                    .midi
                    .get(device_matcher_key)
                    .map(|device_matcher| device_matcher.enabled);
                #[cfg(not(feature = "midi"))]
                Some(false)
            })
    }

    #[cfg(feature = "midi")]
    fn get_available_midi_control_matcher_keys(midi_dm: &MidiMatcherCfg) -> Vec<String> {
        let mut c = Vec::new();
        c.extend(midi_dm.controls.keys().cloned());
        c.extend(PREDEF_CONTROLS.midi_controls.keys().cloned());
        c.sort();
        c.dedup();
        c
    }

    fn get_available_hid_control_matcher_keys(hid_dm: &HidDeviceCfg) -> Vec<String> {
        let mut c = Vec::new();
        c.extend(hid_dm.controls.keys().cloned());
        c.extend(PREDEF_CONTROLS.hid_controls.keys().cloned());
        c.sort();
        c.dedup();
        c
    }

    pub(crate) fn resolve(&mut self) -> Result<()> {
        self.resolve_devices()?;
        self.resolve_dynamic_value_refs()?;
        Ok(())
    }

    fn resolve_devices(&mut self) -> Result<()> {
        #[cfg(feature = "midi")]
        {
            for (device_matcher_key, device_matcher_cfg) in &mut self.devices.midi {
                Self::resolve_midi(device_matcher_key, device_matcher_cfg)
                    .with_context(|| format!("Failed to resolve MIDI device '{}'", device_matcher_key))?;
            }
        }

        for (device_matcher_key, device_matcher_cfg) in &mut self.devices.hid {
            Self::resolve_hid(device_matcher_key, device_matcher_cfg)
                .with_context(|| format!("Failed to resolve HID '{}'", device_matcher_key))?;
            device_matcher_cfg.add_special_force_feedback_controls();
        }

        Ok(())
    }

    fn resolve_dynamic_value_refs(&mut self) -> Result<()> {
        struct CfgDstsAndSrcsVisitor<'s> {
            pub devices: &'s mut DevicesCfgNew,
            pub variables: &'s mut VariablesCfg,
            pub mapping_name: Option<String>,
        }

        impl<'s> traversable::VisitorMut for CfgDstsAndSrcsVisitor<'s> {
            type Break = anyhow::Result<()>;
            fn enter_mut(&mut self, this: &mut dyn core::any::Any) -> std::ops::ControlFlow<Self::Break> {
                if let Some(m) = this.downcast_mut::<Mapping>() {
                    self.mapping_name = Some(m.name.clone());
                }

                if let Some(v) = this.downcast_mut::<DynValueRefs>() {
                    let resolved = Config::resolve_dynamic_value_ref(
                        self.devices,
                        self.variables,
                        v,
                        (self.mapping_name.as_ref().unwrap_or(&String::default())).as_str(),
                    );
                    match resolved {
                        Ok(r) => *v = r,
                        Err(e) => return std::ops::ControlFlow::Break(anyhow::Result::Err(e)),
                    }
                }
                std::ops::ControlFlow::Continue(())
            }

            fn leave_mut(&mut self, this: &mut dyn core::any::Any) -> std::ops::ControlFlow<Self::Break> {
                if this.is::<Mapping>() {
                    self.mapping_name = None;
                }

                if let Some(m) = this.downcast_mut::<Mapping>() {
                    #[cfg(feature = "gui")]
                    if m.transformation.steps.is_empty() {
                        m.transformation.steps.push(TfmStepCfg::default());
                    }

                    m.recompute_metadata(Some(if m.name.is_empty() {
                        m.to_string()
                    } else {
                        m.name.clone()
                    }));
                }
                std::ops::ControlFlow::Continue(())
            }
        }

        let mut visitor = CfgDstsAndSrcsVisitor {
            mapping_name: None,
            devices: &mut self.devices,
            variables: &mut self.variables,
        };

        if let std::ops::ControlFlow::Break(res) = self.mappings.traverse_mut(&mut visitor) {
            return res;
        }

        if let std::ops::ControlFlow::Break(res) = self.ui.traverse_mut(&mut visitor) {
            return res;
        }

        Ok(())
    }

    #[cfg(feature = "midi")]
    fn resolve_midi_control(_device_matcher_key: &str, entry: &mut MidiControlMatcherCfg) -> Result<()> {
        if !entry.from_predefined.is_empty() {
            if let Some(predefined_control) = PREDEF_CONTROLS.midi_controls.get(&entry.from_predefined) {
                if entry.midi_message == Default::default() {
                    entry.midi_message = predefined_control.midi_message.clone();
                }
                if entry.range == Default::default() {
                    entry.range = predefined_control.range;
                }
                if entry.description == Default::default() {
                    entry.description = Some(predefined_control.description.clone());
                }
                entry.midi_message.r#type = predefined_control.midi_message.r#type;
            } else {
                bail!(
                    "Unknown predefined MIDI control '{}'. Available: {:?}",
                    entry.from_predefined,
                    PREDEF_CONTROLS.midi_controls.keys().collect::<Vec<_>>()
                );
            }
        } else if entry.midi_message.r#type == Default::default() {
            bail!("MIDI control has neither 'midi_message' nor valid 'predefined_type': {entry:?}",);
        }

        Ok(())
    }

    fn resolve_hid_control(_device_matcher_key: &str, entry: &mut HidControlMatcherCfg) -> Result<()> {
        if !entry.from_predefined.is_empty() {
            if let Some(predefined_control) = PREDEF_CONTROLS.hid_controls.get(&entry.from_predefined) {
                entry.r#type = predefined_control.r#type;
                if entry.range == Default::default() {
                    entry.range = predefined_control.range;
                }
                if entry.properties == Default::default() {
                    entry.properties = predefined_control.properties.clone();
                }
            } else {
                bail!(
                    "Unknown predefined HID control '{}'. Available: {:?}",
                    entry.from_predefined,
                    PREDEF_CONTROLS.hid_controls.keys().collect::<Vec<_>>()
                );
            }
        } else if entry.r#type == Default::default() {
            bail!("HID control has undefined type and no valid 'predefined' control found: {entry:#?}");
        }

        Ok(())
    }

    pub(crate) fn resolve_hid(device_matcher_key: &str, device: &mut HidDeviceCfg) -> Result<()> {
        for (control_name, control_entry) in &mut device.controls {
            Self::resolve_hid_control(device_matcher_key, control_entry)
                .with_context(|| format!("Failed to expand HID control '{}'", control_name))?;
        }
        device.update_classification();
        Ok(())
    }

    #[cfg(feature = "midi")]
    pub(crate) fn resolve_midi(device_matcher_key: &str, device: &mut MidiMatcherCfg) -> Result<()> {
        for (control_name, control_entry) in &mut device.controls {
            Self::resolve_midi_control(device_matcher_key, control_entry)
                .with_context(|| format!("Failed to expand MIDI control '{}'", control_name))?;
        }
        Ok(())
    }

    fn resolve_dynamic_value_ref(
        devices: &mut DevicesCfgNew,
        variables: &mut VariablesCfg,
        dyn_value: &DynValueRefs,
        mapping_name: &str,
    ) -> Result<DynValueRefs> {
        match dyn_value {
            DynValueRefs::DeviceControlMatcher(d) => {
                if devices.hid.contains_key(&d.device_matcher_key) {
                    let mut device = devices
                        .hid
                        .get_mut(&d.device_matcher_key)
                        .ok_or_else(|| anyhow::anyhow!("Device with key {} not found!", d.device_matcher_key))?
                        .clone();
                    if let Some(hid_control) = device.controls.get(&d.control_matcher_key) {
                        return Ok(DynValueRefs::DeviceControlMatcher(DeviceControlMatcherRef {
                            device_matcher_key: d.device_matcher_key.clone(),
                            control_matcher_key: d.control_matcher_key.clone(),
                            control_matcher: ControlMatchers::Hid(hid_control.clone()),
                        }));
                    }

                    if let Some(predef) = PREDEF_CONTROLS.hid_controls.get(&d.control_matcher_key) {
                        let expanded_control_matcher: HidControlMatcherCfg = predef.clone().into();

                        log::warn!(
                            "Automatically back-filling predefined control {:?} into HID matcher definition for {}, \
                            where it was not found while being referenced in a mapping {}",
                            d.control_matcher_key,
                            d.device_matcher_key,
                            mapping_name
                        );

                        device
                            .controls
                            .insert(d.control_matcher_key.clone(), expanded_control_matcher.clone());

                        let _ = devices.hid.insert(d.device_matcher_key.clone(), device.clone());

                        return Ok(DynValueRefs::DeviceControlMatcher(DeviceControlMatcherRef {
                            device_matcher_key: d.device_matcher_key.clone(),
                            control_matcher_key: d.control_matcher_key.clone(),
                            control_matcher: ControlMatchers::Hid(expanded_control_matcher.clone()),
                        }));
                    }

                    bail!(
                        "Control '{}' not found in device '{}'. Available controls (including predefined): {}",
                        d.control_matcher_key,
                        d.device_matcher_key,
                        devices
                            .hid
                            .get(&d.device_matcher_key)
                            .map(|dm| { Self::get_available_hid_control_matcher_keys(dm).join(", ") })
                            .with_context(
                                || format! {"Couldn't resolve controls for device referenced by key {}.",
                                d.device_matcher_key}
                            )?
                    );
                }
                // --------------------- MIDI ------------------------
                else {
                    #[cfg(not(feature = "midi"))]
                    bail!(
                        "Failed to resolve dynamic value source referring to a device control {dyn_value:#?}.\
                         If you are trying to use configuration using MIDI, please compile with 'midi' feature.",
                    );

                    #[cfg(feature = "midi")]
                    if devices.midi.contains_key(&d.device_matcher_key) {
                        let midi_control = {
                            if let Some(control) = devices
                                .midi
                                .get_mut(&d.device_matcher_key)
                                .unwrap()
                                .controls
                                .get(&d.control_matcher_key)
                            {
                                control.clone()
                            } else if let Some(predef) = PREDEF_CONTROLS.midi_controls.get(&d.control_matcher_key) {
                                log::warn!(
                                    "Automatically back-filling predefined control into midi definition for {}, \
                                    where it was not found while being referenced in a mapping {}",
                                    d.device_matcher_key,
                                    mapping_name
                                );

                                let expanded_control_matcher: MidiControlMatcherCfg = predef.clone().into();

                                let _ = devices
                                    .midi
                                    .get_mut(&d.device_matcher_key)
                                    .unwrap()
                                    .controls
                                    .insert(d.control_matcher_key.to_string(), expanded_control_matcher.clone());

                                expanded_control_matcher
                            } else {
                                bail!(
                                    "Control '{}' not found in device '{}'. Available controls (including predefined): {}",
                                    d.control_matcher_key,
                                    d.device_matcher_key,
                                    devices
                                        .midi
                                        .get(&d.device_matcher_key)
                                        .map(|dm| { Self::get_available_midi_control_matcher_keys(dm).join(", ") })
                                        .with_context(
                                            || format! {"Couldn't resolve controls for device referenced by key {}.",
                                            d.device_matcher_key}
                                        )?
                                );
                            }
                        };

                        Ok(DynValueRefs::DeviceControlMatcher(DeviceControlMatcherRef {
                            device_matcher_key: d.device_matcher_key.clone(),
                            control_matcher_key: d.control_matcher_key.clone(),
                            control_matcher: ControlMatchers::Midi(midi_control),
                        }))
                    } else {
                        bail!("Failed to resolve dynamic value source referring to a device control {dyn_value:#?}",)
                    }
                }
            }
            DynValueRefs::Variable(var) => {
                if let Some((k, v)) = variables.iter().find(|(k, _)| **k == var.variable_key) {
                    Ok(DynValueRefs::Variable(crate::schemas_value::VariableRef {
                        variable_key: k.clone(),
                        variable: v.clone(),
                    }))
                } else {
                    bail!("Variable {} definition is not found", var.variable_key)
                }
            }
        }
    }
}

//------------------------------------------------------
#[derive(Debug)]
pub(crate) struct ConfigManager {
    cfg_file_path_canon: PathBuf,
    cfg_schema_file_path_canon: PathBuf,
    cfg: Config,
    debug: DebugLevel,
}

impl ConfigManager {
    pub(crate) fn get_cfg_file(&self) -> PathBuf {
        self.cfg_file_path_canon.clone()
    }

    pub(crate) fn set_cfg_file(&mut self, cfg_file_path: &Path) -> Result<()> {
        let cfg_file_path_canon = fs::canonicalize(cfg_file_path).context("Failed to canonicalize config file path")?;
        self.cfg_file_path_canon = cfg_file_path_canon.to_owned();
        Ok(())
    }

    pub(crate) fn set_cfg(&mut self, cfg: Config) {
        self.cfg = cfg;
    }

    pub(crate) fn new(cfg_file_path: &Path, debug: DebugLevel) -> Result<Self> {
        let cfg_file_path_canon = fs::canonicalize(cfg_file_path).context("Failed to canonicalize config file path")?;
        Ok(Self {
            cfg_file_path_canon: cfg_file_path_canon.to_owned(),
            cfg_schema_file_path_canon: cfg_file_path_canon.with_file_name(APP_CONFIG_SCHEMA_FILE_CFG_RELATIVE),
            cfg: Config::new(cfg_file_path_canon),
            debug,
        })
    }

    pub(crate) fn load(&mut self) -> Result<()> {
        log::info!("Loading user config from {}", self.cfg_file_path_canon.display());

        /* Generate and save config scheme. */
        let schema = schemars::schema_for!(Config);
        {
            if self.debug.is_on() {
                log::debug!(
                    "Generating and saving config schema into {}",
                    self.cfg_schema_file_path_canon.as_path().display()
                );
            }

            if let Err(e) = fs::write(
                self.cfg_schema_file_path_canon.as_path(),
                serde_json::to_string_pretty(&schema).context("Failed to generate schema from internal spec")?,
            ) {
                log::warn!(
                    "Failed to update schema at {} based on internal spec due to: {:?}",
                    self.cfg_schema_file_path_canon.as_path().display(),
                    e
                );
            };
        }

        if !self.cfg_file_path_canon.exists() {
            // log::warn!(
            //     "Configuration file not found, creating default: {:?}",
            //     self.cfg_file_path_canon
            // );
            // self.cfg = Config::default();
            // let _ = self.save(&None, &None);

            log::error!("Config file is not found at {:?}", self.cfg_file_path_canon);
            bail!("Config file not found at {:?}", self.cfg_file_path_canon);
        }

        let txt = fs::read_to_string(&self.cfg_file_path_canon).context("Failed to read config file")?;
        let parse_res: Result<Config, serde_saphyr::Error> = serde_saphyr::from_str(&txt);

        match parse_res {
            Ok(cfg) => self.cfg = cfg,
            Err(e) => {
                if let Some(location) = e.location()
                    && (location.line() != 0 || location.column() != 0)
                {
                    let mut ee = e.render();
                    ee += &self.load_print_cfg_error_context(&txt, location.line().saturating_sub(5u64) as usize, 7);
                    bail!(ee);
                } else {
                    bail!(e);
                }
            }
        }

        self.cfg.cfg_file = self.cfg_file_path_canon.clone();
        self.cfg.resolve()?;

        // TODO: !!! sanitizer pass: WithRuntimeId get_id() != 0 and WithMappedCtls get_control_type() != Unhandled

        /* Dumping predefined controls templates for reference. */
        {
            let predef_ctls_dump_path = self
                .cfg_file_path_canon
                .parent()
                .expect("Config file path should have a parent directory")
                .join("predefined_controls_dump.yaml");

            if self.debug.is_on() {
                log::debug!(
                    "Generating and saving predefined controls templates into {}",
                    predef_ctls_dump_path.as_path().display()
                );
            }

            if let Err(e) = fs::write(
                predef_ctls_dump_path.as_path(),
                serde_saphyr::to_string(&*PREDEF_CONTROLS)
                    .context("Failed to generate text YAML from predefined controls spec.")?,
            ) {
                log::warn!(
                    "Failed to update predefined controls at {} based on internal spec due to: {:?}",
                    predef_ctls_dump_path.as_path().display(),
                    e
                );
            };
        }

        Ok(())
    }

    fn load_print_cfg_error_context(&mut self, src: &str, line0: usize, after: usize) -> String {
        let start = line0;
        let end = line0.saturating_add(after);
        let mut out = String::from("");
        out += " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ";
        out += "... Context around erroneous config snippet: \n";
        for (i, line) in src.lines().enumerate() {
            if i < start {
                continue;
            } else if i > end {
                break;
            }
            out += &format!("{:>6} | {}", i + 1, line);
        }
        out += " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ";
        out
    }

    // -------------------------------------------------------
    #[allow(unused)]
    pub(crate) fn save(&self, file: &Option<PathBuf>, suffix: &Option<String>) -> Result<()> {
        let file = file.clone().unwrap_or_else(|| {
            let mut p = self.cfg_file_path_canon.clone();
            if let Some(suffix) = suffix {
                p.set_extension(suffix);
            }
            p
        });
        fs::write(&file, self.cfg_ref().get_yaml_str()).context("Failed to write config file")?;
        Ok(())
    }

    pub(crate) fn cfg_ref(&self) -> &Config {
        &self.cfg
    }

    pub(crate) fn cfg_mut(&mut self) -> &mut Config {
        &mut self.cfg
    }
}

// ------------------------------------------------------------
// TODO?: partially could generate from mapped controls macro (will need to add relevant range and properties info where appropriate).
pub(crate) static PREDEF_CONTROLS: LazyLock<ControlsPredefinedCfg> = LazyLock::new(|| {
    let mut s: String = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/config_hid_predefined_controls.yaml"
    ))
    .into();

    #[cfg(feature = "midi")]
    {
        s += include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/src/config_midi_predefined_controls.yaml"
        ));
    }

    serde_saphyr::from_str(&s).expect("Failed to parse built-in predefined controls")
});
