use crate::debug::DebugLevel;
use crate::hid_manager::WithDeviceClassification;
use crate::schemas_cfg::*;
use crate::schemas_control_matcher::ControlMatchers;
use crate::schemas_hid::{HidControlMatcherCfg, HidDeviceCfg};
use crate::schemas_mapping::Mapping;
#[cfg(feature = "midi")]
use crate::schemas_midi::{MidiControlMatcherCfg, MidiMatcherCfg};
use crate::schemas_predefined::ControlsPredefinedCfg;
use crate::schemas_transform::*;

use crate::schemas_value::{DeviceControlMatcherRef, DynValueRefs, WithNumInterval, WithRelativity};
use anyhow::{Context, Result, bail};
use chrono::Utc;

use std::fs;
use std::path::{Path, PathBuf};
use std::sync::LazyLock;
use traversable::TraversableMut;
// use yaml_merge_keys::merge_keys_serde;

#[cfg(feature = "more_debug")]
pub const MORE_DEBUG: bool = true;
#[cfg(not(feature = "more_debug"))]
pub const MORE_DEBUG: bool = false;

pub const APP_VERSION_STR: &str = env!("CARGO_PKG_VERSION");
pub const CONFIG_VERSION_STR: &str = APP_VERSION_STR;
pub const APP_DEFAULT_CONFIG_FILE: &str = "conf/default.yaml";
pub const APP_DEFAULT_PREDEF_CONFIG_FILE_CFG_RELATIVE: &str = "predefined.yaml";
pub const APP_CONFIG_SCHEMA_FILE_CFG_RELATIVE: &str = "scheme.json";
pub const APP_AUTHORS: &str = env!("CARGO_PKG_AUTHORS"); // .. and small furry creatures from Alpha Centauri.
pub const APP_NAME: &str = env!("CARGO_PKG_NAME");
pub const APP_COMMAND_NAME: &str = "mmvj";
pub const APP_LONG_NAME: &str = "MMVJ: HID/MIDI transforming I/O mapper and force-feedback-enabled virtual HID manager";
pub const APP_ABOUT: &str = env!("CARGO_PKG_DESCRIPTION");
pub const APP_LONG_ABOUT: &str = APP_ABOUT;
pub const APP_DEFAULT_NO_HOT_RELOAD: &str = "false";
pub const APP_DEFAULT_LATENCY_STR: &str = "normal";
#[cfg(debug_assertions)]
pub const APP_DEFAULT_MAX_LOG_LEVEL: &str = "warn";
#[cfg(not(debug_assertions))]
pub const APP_DEFAULT_MAX_LOG_LEVEL: &str = "error";
pub const MIN_BASE_FREQ_HZ: u32 = 10;
pub const MAX_BASE_FREQ_HZ: u32 = 1000;

#[cfg(not(feature = "gui"))]
pub const GUI_ENABLED_CONST: bool = false;
#[cfg(feature = "gui")]
pub const GUI_ENABLED_CONST: bool = true;

#[cfg(not(feature = "midi"))]
pub const MIDI_ENABLED_CONST: bool = false;
#[cfg(feature = "midi")]
pub const MIDI_ENABLED_CONST: bool = true;

//-----------------------------------------------------------------
pub(crate) trait WithSanitize {
    fn sanitize_inplace(&mut self);
    #[allow(unused)]
    fn sanitize(mut self) -> Self
    where
        Self: Sized,
    {
        self.sanitize_inplace();
        self
    }
}

impl Config {
    fn new(cfg_file: PathBuf) -> Self {
        Self {
            cfg_file,
            ..Default::default()
        }
    }

    pub(crate) fn get_yaml_str(&self) -> String {
        let mut yaml = format!(
            "# {APP_NAME} configuration.\n\
             # {APP_NAME} version: {CONFIG_VERSION_STR}\n\
             # Autogenerated at: {}\n\n",
            Utc::now()
        );
        yaml += serde_saphyr::to_string(self)
            .expect("Failed to serialize config.")
            .as_str();
        yaml
    }

    pub(crate) fn recompute_mappings_metadata(&mut self) {
        for mapping in self.mappings.iter_mut() {
            mapping
                .transformation
                .recompute_metadata(AutoOrManual::Auto(crate::schemas_value::InputValueMetadata {
                    relativity: mapping.src.get_relativity(),
                    interval: mapping.src.get_interval(),
                }));
        }
    }

    pub(crate) fn _device_matcher_exists_and_is_enabled(&self, device_matcher_key: &str) -> Option<bool> {
        // TODO: common iface for device matcher on config level.
        self.devices
            .hid
            .get(device_matcher_key)
            .map(|device_matcher| device_matcher.is_enabled())
            .or_else(|| {
                #[cfg(feature = "midi")]
                return self
                    .devices
                    .midi
                    .get(device_matcher_key)
                    .map(|device_matcher| device_matcher.enabled);
                #[cfg(not(feature = "midi"))]
                Some(false)
            })
    }

    #[cfg(feature = "midi")]
    fn get_available_midi_control_matcher_keys(&self, device_matcher_key: &str) -> Result<Vec<String>> {
        if let Some(dm) = self.devices.midi.get(device_matcher_key) {
            let mut c = Vec::new();
            c.extend(dm.controls.keys().cloned());
            c.extend(PREDEF_CONTROLS.midi_controls.keys().cloned());
            c.sort();
            c.dedup();
            Ok(c)
        } else {
            bail!("Device definition is not found for {device_matcher_key}");
        }
    }

    fn get_availale_hid_control_matcher_keys(&self, device_matcher_key: &str) -> Result<Vec<String>> {
        if let Some(dm) = self.devices.hid.get(device_matcher_key) {
            let mut c = Vec::new();
            c.extend(dm.controls.keys().cloned());
            c.extend(PREDEF_CONTROLS.hid_controls.keys().cloned());
            c.sort();
            c.dedup();
            Ok(c)
        } else {
            bail!("Device definition is not found for {device_matcher_key}");
        }
    }

    pub(crate) fn resolve(&mut self) -> Result<()> {
        self.resolve_devices()?;
        self.resolve_dynamic_value_refs()?;
        Ok(())
    }

    fn resolve_devices(&mut self) -> Result<()> {
        #[cfg(feature = "midi")]
        {
            let mut tmp = self.devices.midi.clone();
            for (device_matcher_key, device_matcher_cfg) in &mut tmp {
                self.resolve_midi(device_matcher_key, device_matcher_cfg)
                    .with_context(|| format!("Failed to resolve MIDI device '{}'", device_matcher_key))?;
            }
            self.devices.midi = tmp;
        }

        let mut tmp = self.devices.hid.clone();
        for (device_matcher_key, device_matcher_cfg) in &mut tmp {
            self.resolve_hid(device_matcher_key, device_matcher_cfg)
                .with_context(|| format!("Failed to resolve HID '{}'", device_matcher_key))?;
            device_matcher_cfg.add_special_force_feedback_controls();
        }
        self.devices.hid = tmp;

        Ok(())
    }

    fn resolve_dynamic_value_refs(&mut self) -> Result<()> {
        struct CfgDstsAndSrcsVisitor<'s> {
            pub cfg: &'s mut Config,
            pub mapping_name: Option<String>,
        }

        impl<'s> traversable::VisitorMut for CfgDstsAndSrcsVisitor<'s> {
            type Break = ();
            fn enter_mut(&mut self, this: &mut dyn core::any::Any) -> std::ops::ControlFlow<Self::Break> {
                if let Some(m) = this.downcast_mut::<Mapping>() {
                    self.mapping_name = Some(m.name.clone());
                }
                if let Some(v) = this.downcast_mut::<DynValueRefs>() {
                    *v = self
                        .cfg
                        .resolve_dynamic_value_ref(
                            v,
                            (self.mapping_name.as_ref().unwrap_or(&String::default())).as_str(),
                        )
                        .unwrap_or(v.clone());
                }
                std::ops::ControlFlow::Continue(())
            }

            fn leave_mut(&mut self, this: &mut dyn core::any::Any) -> std::ops::ControlFlow<Self::Break> {
                if this.is::<Mapping>() {
                    self.mapping_name = None;
                }

                if let Some(m) = this.downcast_mut::<Mapping>() {
                    #[cfg(feature = "gui")]
                    if m.transformation.steps.is_empty() {
                        m.transformation.steps.push(TfmStepCfg::default());
                    }

                    m.recompute_metadata(Some(if m.name.is_empty() {
                        m.to_string()
                    } else {
                        m.name.clone()
                    }));
                }
                std::ops::ControlFlow::Continue(())
            }
        }

        let mut cfg_tmp = self.clone();
        let _ = cfg_tmp.traverse_mut(&mut CfgDstsAndSrcsVisitor {
            cfg: self,
            mapping_name: None,
        });
        *self = cfg_tmp;

        Ok(())
    }

    #[cfg(feature = "midi")]
    fn resolve_midi_control(&self, _device_matcher_key: &str, entry: &mut MidiControlMatcherCfg) -> Result<()> {
        if !entry.from_predefined.is_empty() {
            if let Some(predefined_control) = PREDEF_CONTROLS.midi_controls.get(&entry.from_predefined) {
                if entry.midi_message == Default::default() {
                    entry.midi_message = predefined_control.midi_message.clone();
                }
                if entry.range == Default::default() {
                    entry.range = predefined_control.range;
                }
                if entry.description == Default::default() {
                    entry.description = Some(predefined_control.description.clone());
                }
                entry.midi_message.r#type = predefined_control.midi_message.r#type;
            } else {
                bail!(
                    "Unknown predefined MIDI control '{}'. Available: {:?}",
                    entry.from_predefined,
                    PREDEF_CONTROLS.midi_controls.keys().collect::<Vec<_>>()
                );
            }
        } else if entry.midi_message.r#type == Default::default() {
            bail!("MIDI control has neither 'midi_message' nor valid 'predefined_type': {entry:?}",);
        }

        Ok(())
    }

    fn resolve_hid_control(&self, _device_matcher_key: &str, entry: &mut HidControlMatcherCfg) -> Result<()> {
        if !entry.from_predefined.is_empty() {
            if let Some(predefined_control) = PREDEF_CONTROLS.hid_controls.get(&entry.from_predefined) {
                entry.r#type = predefined_control.r#type;
                if entry.range == Default::default() {
                    entry.range = predefined_control.range;
                }
                if entry.properties == Default::default() {
                    entry.properties = predefined_control.properties.clone();
                }
            } else {
                bail!(
                    "Unknown predefined HID control '{}'. Available: {:?}",
                    entry.from_predefined,
                    PREDEF_CONTROLS.hid_controls.keys().collect::<Vec<_>>()
                );
            }
        } else if entry.r#type == Default::default() {
            bail!("HID control has undefined type and no valid 'predefined' control found: {entry:#?}");
        }

        Ok(())
    }

    pub(crate) fn resolve_hid(&self, device_matcher_key: &str, device: &mut HidDeviceCfg) -> Result<()> {
        for (control_name, control_entry) in &mut device.controls {
            self.resolve_hid_control(device_matcher_key, control_entry)
                .with_context(|| format!("Failed to expand HID control '{}'", control_name))?;
        }
        device.update_classification();
        Ok(())
    }

    #[cfg(feature = "midi")]
    pub(crate) fn resolve_midi(&mut self, device_matcher_key: &str, device: &mut MidiMatcherCfg) -> Result<()> {
        for (control_name, control_entry) in &mut device.controls {
            self.resolve_midi_control(device_matcher_key, control_entry)
                .with_context(|| format!("Failed to expand MIDI control '{}'", control_name))?;
        }
        Ok(())
    }

    fn resolve_dynamic_value_ref(&mut self, dyn_value: &DynValueRefs, mapping_name: &str) -> Result<DynValueRefs> {
        match dyn_value {
            DynValueRefs::DeviceControlMatcher(d) => {
                if self.devices.hid.contains_key(&d.device_matcher_key) {
                    let mut device = self
                        .devices
                        .hid
                        .get_mut(&d.device_matcher_key)
                        .ok_or_else(|| anyhow::anyhow!("Device with key {} not found!", d.device_matcher_key))?
                        .clone();
                    if let Some(hid_control) = device.controls.get(&d.control_key) {
                        return Ok(DynValueRefs::DeviceControlMatcher(DeviceControlMatcherRef {
                            device_matcher_key: d.device_matcher_key.clone(),
                            control_key: d.control_key.clone(),
                            control_matcher: ControlMatchers::Hid(hid_control.clone()),
                        }));
                    }

                    if let Some(predef) = PREDEF_CONTROLS.hid_controls.get(&d.control_key) {
                        let expanded_control_matcher: HidControlMatcherCfg = predef.clone().into();

                        log::warn!(
                            "Automatically back-filling predefined control {:?} into HID matcher definition for {}, \
                            where it was not found while being referenced in a mapping {}",
                            d.control_key,
                            d.device_matcher_key,
                            mapping_name
                        );

                        device
                            .controls
                            .insert(d.control_key.clone(), expanded_control_matcher.clone());

                        let _ = self.devices.hid.insert(d.device_matcher_key.clone(), device.clone());

                        return Ok(DynValueRefs::DeviceControlMatcher(DeviceControlMatcherRef {
                            device_matcher_key: d.device_matcher_key.clone(),
                            control_key: d.control_key.clone(),
                            control_matcher: ControlMatchers::Hid(expanded_control_matcher.clone()),
                        }));
                    }

                    bail!(
                        "Control '{}' not found in device '{}'. Available controls (including predefined): {}",
                        d.control_key,
                        d.device_matcher_key,
                        self.get_availale_hid_control_matcher_keys(&d.device_matcher_key)
                            .context("Couldn't resolve controls for device.")?
                            .join(", ")
                    );
                }
                // --------------------- MIDI ------------------------
                else {
                    #[cfg(not(feature = "midi"))]
                    bail!(
                        "Failed to resolve dynamic value source referring to a device control {dyn_value:#?}.\
                         If you are trying to use configuration using MIDI, please compile with 'midi' feature.",
                    );

                    #[cfg(feature = "midi")]
                    if self.devices.midi.contains_key(&d.device_matcher_key) {
                        let midi_control = {
                            if let Some(control) = self
                                .devices
                                .midi
                                .get_mut(&d.device_matcher_key)
                                .unwrap()
                                .controls
                                .get(&d.control_key)
                            {
                                control.clone()
                            } else if let Some(predef) = PREDEF_CONTROLS.midi_controls.get(&d.control_key) {
                                log::warn!(
                                    "Automatically back-filling predefined control {:?} into midi definition for {}, \
                                    where it was not found while being referenced in a mapping {}",
                                    d.control_matcher,
                                    d.device_matcher_key,
                                    mapping_name
                                );

                                let expanded_control_matcher: MidiControlMatcherCfg = predef.clone().into();

                                let _ = self
                                    .devices
                                    .midi
                                    .get_mut(&d.device_matcher_key)
                                    .unwrap()
                                    .controls
                                    .insert(d.control_key.to_string(), expanded_control_matcher.clone());

                                expanded_control_matcher
                            } else {
                                bail!(
                                    "Control '{}' not found in device '{}'. Available controls (including predefined): {}",
                                    d.control_key,
                                    d.device_matcher_key,
                                    self.get_available_midi_control_matcher_keys(&d.device_matcher_key)
                                        .context("Failed to get available controls for device.")?
                                        .join(", ")
                                );
                            }
                        };

                        Ok(DynValueRefs::DeviceControlMatcher(DeviceControlMatcherRef {
                            device_matcher_key: d.device_matcher_key.clone(),
                            control_key: d.control_key.clone(),
                            control_matcher: ControlMatchers::Midi(midi_control),
                        }))
                    } else {
                        bail!("Failed to resolve dynamic value source referring to a device control {dyn_value:#?}",)
                    }
                }
            }
            DynValueRefs::Variable(var) => {
                if let Some((k, v)) = self.variables.iter().find(|(k, _)| **k == var.variable_key) {
                    Ok(DynValueRefs::Variable(crate::schemas_value::VariableRef {
                        variable_key: k.clone(),
                        variable: v.clone(),
                    }))
                } else {
                    bail!("Variable {var:#?} definition is not found")
                }
            }
        }
    }
}

//------------------------------------------------------
#[derive(Debug)]
pub(crate) struct ConfigManager {
    cfg_file_path_canon: PathBuf,
    cfg_schema_file_path_canon: PathBuf,
    cfg: Config,
    debug: DebugLevel,
}

impl ConfigManager {
    pub(crate) fn get_cfg_file(&self) -> PathBuf {
        self.cfg_file_path_canon.clone()
    }

    pub(crate) fn set_cfg_file(&mut self, cfg_file_path: &Path) -> Result<()> {
        let cfg_file_path_canon = fs::canonicalize(cfg_file_path).context("Failed to canonicalize config file path")?;
        self.cfg_file_path_canon = cfg_file_path_canon.to_owned();
        Ok(())
    }

    pub(crate) fn set_cfg(&mut self, cfg: Config) {
        self.cfg = cfg;
    }

    pub(crate) fn new(cfg_file_path: &Path, debug: DebugLevel) -> Result<Self> {
        let cfg_file_path_canon = fs::canonicalize(cfg_file_path).context("Failed to canonicalize config file path")?;
        Ok(Self {
            cfg_file_path_canon: cfg_file_path_canon.to_owned(),
            cfg_schema_file_path_canon: cfg_file_path_canon.with_file_name(APP_CONFIG_SCHEMA_FILE_CFG_RELATIVE),
            cfg: Config::new(cfg_file_path_canon),
            debug,
        })
    }

    pub(crate) fn load(&mut self) -> Result<()> {
        log::info!("Loading user config from {}", self.cfg_file_path_canon.display());

        /* Generate and save config scheme. */
        let schema = schemars::schema_for!(Config);
        {
            if self.debug.is_on() {
                log::debug!(
                    "Generating and saving config schema into {}",
                    self.cfg_schema_file_path_canon.as_path().display()
                );
            }

            if let Err(e) = fs::write(
                self.cfg_schema_file_path_canon.as_path(),
                serde_json::to_string_pretty(&schema).context("Failed to generate schema from internal spec")?,
            ) {
                log::warn!(
                    "Failed to update schema at {} based on internal spec due to: {:?}",
                    self.cfg_schema_file_path_canon.as_path().display(),
                    e
                );
            };
        }

        if !self.cfg_file_path_canon.exists() {
            // log::warn!(
            //     "Configuration file not found, creating default: {:?}",
            //     self.cfg_file_path_canon
            // );
            // self.cfg = Config::default();
            // let _ = self.save(&None, &None);

            log::error!("Config file is not found at {:?}", self.cfg_file_path_canon);
            bail!("Config file not found at {:?}", self.cfg_file_path_canon);
        }

        let txt = fs::read_to_string(&self.cfg_file_path_canon).context("Failed to read config file")?;
        let parse_res: Result<Config, serde_saphyr::Error> = serde_saphyr::from_str(&txt);

        match parse_res {
            Ok(cfg) => self.cfg = cfg,
            Err(e) => {
                if let Some(location) = e.location()
                    && (location.line() != 0 || location.column() != 0)
                {
                    let mut ee = e.render();
                    ee += &self.load_print_cfg_error_context(&txt, location.line().saturating_sub(5u64) as usize, 7);
                    bail!(ee);
                } else {
                    bail!(e);
                }
            }
        }

        self.cfg.cfg_file = self.cfg_file_path_canon.clone();
        self.cfg.resolve()?;

        // TODO: !!! sanitizer pass: WithRuntimeId get_id() != 0 and WithMappedCtls get_control_type() != Unhandled

        /* Dumping predefined controls templates for reference. */
        {
            let predef_ctls_dump_path = self
                .cfg_file_path_canon
                .parent()
                .expect("Config file path should have a parent directory")
                .join("predefined_controls_dump.yaml");

            if self.debug.is_on() {
                log::debug!(
                    "Generating and saving predefined controls templates into {}",
                    predef_ctls_dump_path.as_path().display()
                );
            }

            if let Err(e) = fs::write(
                predef_ctls_dump_path.as_path(),
                serde_saphyr::to_string(&*PREDEF_CONTROLS)
                    .context("Failed to generate text YAML from predefined controls spec.")?,
            ) {
                log::warn!(
                    "Failed to update predefined controls at {} based on internal spec due to: {:?}",
                    predef_ctls_dump_path.as_path().display(),
                    e
                );
            };
        }

        Ok(())
    }

    fn load_print_cfg_error_context(&mut self, src: &str, line0: usize, after: usize) -> String {
        let start = line0;
        let end = line0.saturating_add(after);
        let mut out = String::from("");
        out += " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ";
        out += "... Context around erroneous config snippet: \n";
        for (i, line) in src.lines().enumerate() {
            if i < start {
                continue;
            } else if i > end {
                break;
            }
            out += &format!("{:>6} | {}", i + 1, line);
        }
        out += " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ";
        out
    }

    // -------------------------------------------------------
    #[allow(unused)]
    pub(crate) fn save(&self, file: &Option<PathBuf>, suffix: &Option<String>) -> Result<()> {
        let file = file.clone().unwrap_or_else(|| {
            let mut p = self.cfg_file_path_canon.clone();
            if let Some(suffix) = suffix {
                p.set_extension(suffix);
            }
            p
        });
        fs::write(&file, self.cfg_ref().get_yaml_str()).context("Failed to write config file")?;
        Ok(())
    }

    pub(crate) fn cfg_ref(&self) -> &Config {
        &self.cfg
    }

    pub(crate) fn cfg_mut(&mut self) -> &mut Config {
        &mut self.cfg
    }
}

// ------------------------------------------------------------

// TODO?: generate from mapped controls macro (will need to add relevant range and properties info where appropriate).
pub(crate) static PREDEF_CONTROLS: LazyLock<ControlsPredefinedCfg> = LazyLock::new(|| {
    let mut s: String = r#"

#############################################################################
#    
hid_controls:
  FORCE_FEEDBACK_X:
    type: FORCE_FEEDBACK_X
    range: [ -32768, 32767 ]
    properties: { resolution: 1, fuzz: 0, flat: 0 }
    initial_value: 0
    description: "Special, fake, control to expose force feedback X component coming from device. Currently R/O, write ignored (could reuse it to inject Constant force on unowned HID though)."

  FORCE_FEEDBACK_Y:
    type: FORCE_FEEDBACK_Y
    range: [ -32768, 32767 ]
    properties: { resolution: 1, fuzz: 0, flat: 0 }
    initial_value: 0
    description: "Special, fake, control to expose force feedback Y component coming from device. Currently R/O, write ignored (could reuse it to inject Constant force on unowned HID though)."

  ABS_X:
    type: ABS_X
    range: [ 0, 32767 ] ## <--- this works by default with ffcfstress utility ##... and this doesn't ---> [-32768, 32767]
    properties: { resolution: 1, fuzz: 0, flat: 0 }
    initial_value: 0
    description: "Primary X-axis (left stick horizontal), positive range."

  ABS_Y:
    type: ABS_Y
    range: [ 0, 32767 ]
    properties: { resolution: 1, fuzz: 0, flat: 0 }
    initial_value: 0
    description: "Primary Y-axis (left stick vertical)"

  ABS_Z:
    type: ABS_Z
    range: [ 0, 32767 ]
    properties: { resolution: 1, fuzz: 0, flat: 0 }
    initial_value: 0
    description: "Z-axis (left trigger analog)"

  ABS_RX:
    type: ABS_RX
    range: [ 0, 32767 ]
    properties: { resolution: 1, fuzz: 0, flat: 0 }
    initial_value: 0
    description: "Right X-axis (right stick horizontal)"

  ABS_RY:
    type: ABS_RY
    range: [ 0, 32767 ]
    properties: { resolution: 1, fuzz: 0, flat: 0 }
    initial_value: 0
    description: "Right Y-axis (right stick vertical)"

  ABS_RZ:
    type: ABS_RZ
    range: [ 0, 32767 ]
    properties: { resolution: 1, fuzz: 0, flat: 0 }
    initial_value: 0
    description: "Right Z-axis (right trigger analog)"

  ABS_WHEEL:
    type: ABS_WHEEL
    range: [ 0, 32767 ]
    properties: { resolution: 1, fuzz: 0, flat: 0 }
    initial_value: 0
    description: "Steering wheel axis"

  ABS_GAS:
    type: ABS_GAS
    range: [0, 32767]
    properties: { resolution: 1, fuzz: 0, flat: 0 }
    initial_value: 0
    description: "Gas/throttle pedal"

  ABS_BRAKE:
    type: ABS_BRAKE
    range: [0, 32767]
    properties: { resolution: 1, fuzz: 0, flat: 0 }
    initial_value: 0
    description: "Brake pedal"

  ABS_HAT0X:
    type: ABS_HAT0_X # TODO: HAT0X
    range: [-1, 1]
    initial_value: 0
    description: "D-pad horizontal"

  ABS_HAT0Y:
    type: ABS_HAT0_Y
    range: [-1, 1]
    initial_value: 0
    description: "D-pad vertical"

  # Buttons - Xbox style naming
  BTN_A:
    type: BTN_SOUTH
    range: [0, 1]
    initial_value: 0
    description: "A button (Xbox) / Cross (PlayStation)"

  BTN_B:
    type: BTN_EAST
    range: [0, 1]
    initial_value: 0
    description: "B button (Xbox) / Circle (PlayStation)"

  BTN_X:
    type: BTN_NORTH
    range: [0, 1]
    initial_value: 0
    description: "X button (Xbox) / Square (PlayStation)"

  BTN_Y:
    type: BTN_WEST
    range: [0, 1]
    initial_value: 0
    description: "Y button (Xbox) / Triangle (PlayStation)"

  # Buttons - Linux evdev naming (aliases)
  BTN_SOUTH:
    type: BTN_SOUTH
    range: [0, 1]
    initial_value: 0
    description: "South button (A on Xbox)"

  BTN_EAST:
    type: BTN_EAST
    range: [0, 1]
    initial_value: 0
    description: "East button (B on Xbox)"

  BTN_NORTH:
    type: BTN_NORTH
    range: [0, 1]
    initial_value: 0
    description: "North button (X on Xbox)"

  BTN_WEST:
    type: BTN_WEST
    range: [0, 1]
    initial_value: 0
    description: "West button (Y on Xbox)"

  # Shoulder buttons
  # BTN_TL:
  #   type: BTN_TL
  #   range: [0, 1]
  #   initial_value: 0
  #   description: "Left shoulder button (LB/L1)"

  # BTN_TR:
  #   type: BTN_TR
  #   range: [0, 1]
  #   initial_value: 0
  #   description: "Right shoulder button (RB/R1)"

  # BTN_TL2:
  #   type: BTN_TL2
  #   range: [0, 1]
  #   initial_value: 0
  #   description: "Left trigger button (LT/L2)"

  # BTN_TR2:
  #   type: BTN_TR2
  #   range: [0, 1]
  #   initial_value: 0
  #   description: "Right trigger button (RT/R2)"

  # Thumbstick buttons
  # BTN_THUMBL:
  #   type: BTN_THUMBL
  #   range: [0, 1]
  #   initial_value: 0
  #   description: "Left thumbstick press (L3)"

  # BTN_THUMBR:
  #   type: BTN_THUMBR
  #   range: [0, 1]
  #   initial_value: 0
  #   description: "Right thumbstick press (R3)"

  BTN_SELECT:
    type: BTN_SELECT
    range: [0, 1]
    initial_value: 0
    description: "Select/Back button"

  BTN_START:
    type: BTN_START
    range: [0, 1]
    initial_value: 0
    description: "Start/Menu button"

  BTN_TRIGGER:
    type: BTN_TRIGGER
    range: [0, 1]
    initial_value: 0
    description: ""

  # ----------------
  # Mouse Controls
  # ----------------
  # Relative movement
  REL_X:
    type: REL_X
    range: [-127, 127]
    description: "Relative X movement (counts per tick)"

  REL_Y:
    type: REL_Y
    range: [-127, 127]
    description: "Relative Y movement (counts per tick)"

  # Wheels
  REL_WHEEL:
    type: REL_WHEEL
    range: [-10, 10]
    description: "Vertical scroll wheel (steps)"

  REL_HWHEEL:
    type: REL_HWHEEL
    range: [-10, 10]
    description: "Horizontal scroll wheel (steps)"

  # High-resolution wheels (if available)
  REL_WHEEL_HI_RES:
    type: REL_WHEEL_HI_RES
    range: [-120, 120] ## Please test with your hi res mouse and report if app warns you about clamping all the time.
                       ## Most probably this must be extended.
    description: "High-resolution vertical wheel"

  REL_HWHEEL_HI_RES:
    type: REL_HWHEEL_HI_RES
    range: [-120, 120] ## Please test with your hi res mouse and report if app warns you about clamping all the time.
                       ## Most probably this must be extended.
    description: "High-resolution vertical wheel"

  # Buttons
  BTN_LEFT:
    type: BTN_LEFT
    range: [0, 1]
    description: "Left mouse button"

  BTN_RIGHT:
    type: BTN_RIGHT
    range: [0, 1]
    description: "Right mouse button"

  BTN_MIDDLE:
    type: BTN_MIDDLE
    range: [0, 1]
    description: "Middle mouse button"

  BTN_SIDE:
    type: BTN_SIDE
    range: [0, 1]
    description: "Side button (back)"

  BTN_EXTRA:
    type: BTN_EXTRA
    range: [0, 1]
    description: "Extra button (forward)"

  # --- Alphanumeric Keys ---
  KEY_ESC:
    type: KEY_ESC
    range: [0, 2]
    description: "Escape key"

  KEY_1:
    type: KEY_1
    range: [0, 2]
    description: "Number 1 key"

  KEY_2:
    type: KEY_2
    range: [0, 2]
    description: "Number 2 key"

  KEY_3:
    type: KEY_3
    range: [0, 2]
    description: "Number 3 key"

  KEY_4:
    type: KEY_4
    range: [0, 2]
    description: "Number 4 key"

  KEY_5:
    type: KEY_5
    range: [0, 2]
    description: "Number 5 key"

  KEY_6:
    type: KEY_6
    range: [0, 2]
    description: "Number 6 key"

  KEY_7:
    type: KEY_7
    range: [0, 2]
    description: "Number 7 key"

  KEY_8:
    type: KEY_8
    range: [0, 2]
    description: "Number 8 key"

  KEY_9:
    type: KEY_9
    range: [0, 2]
    description: "Number 9 key"

  KEY_0:
    type: KEY_0
    range: [0, 2]
    description: "Number 0 key"

  KEY_MINUS:
    type: KEY_MINUS
    range: [0, 2]
    description: "Minus/Dash key"

  KEY_EQUAL:
    type: KEY_EQUAL
    range: [0, 2]
    description: "Equals key"

  KEY_BACKSPACE:
    type: KEY_BACKSPACE
    range: [0, 2]
    description: "Backspace key"

  KEY_TAB:
    type: KEY_TAB
    range: [0, 2]
    description: "Tab key"

  KEY_Q:
    type: KEY_Q
    range: [0, 2]
    description: "Q key"

  KEY_W:
    type: KEY_W
    range: [0, 2]
    description: "W key"

  KEY_E:
    type: KEY_E
    range: [0, 2]
    description: "E key"

  KEY_R:
    type: KEY_R
    range: [0, 2]
    description: "R key"

  KEY_T:
    type: KEY_T
    range: [0, 2]
    description: "T key"

  KEY_Y:
    type: KEY_Y
    range: [0, 2]
    description: "Y key"

  KEY_U:
    type: KEY_U
    range: [0, 2]
    description: "U key"

  KEY_I:
    type: KEY_I
    range: [0, 2]
    description: "I key"

  KEY_O:
    type: KEY_O
    range: [0, 2]
    description: "O key"

  KEY_P:
    type: KEY_P
    range: [0, 2]
    description: "P key"

  KEY_LEFTBRACE:
    type: KEY_LEFTBRACE
    range: [0, 2]
    description: "Left bracket/key"

  KEY_RIGHTBRACE:
    type: KEY_RIGHTBRACE
    range: [0, 2]
    description: "Right bracket/key"

  KEY_ENTER:
    type: KEY_ENTER
    range: [0, 2]
    description: "Enter/Return key"

  KEY_LEFTCTRL:
    type: KEY_LEFTCTRL
    range: [0, 2]
    description: "Left Control modifier key"

  KEY_A:
    type: KEY_A
    range: [0, 2]
    description: "A key"

  KEY_S:
    type: KEY_S
    range: [0, 2]
    description: "S key"

  KEY_D:
    type: KEY_D
    range: [0, 2]
    description: "D key"

  KEY_F:
    type: KEY_F
    range: [0, 2]
    description: "F key"

  KEY_G:
    type: KEY_G
    range: [0, 2]
    description: "G key"

  KEY_H:
    type: KEY_H
    range: [0, 2]
    description: "H key"

  KEY_J:
    type: KEY_J
    range: [0, 2]
    description: "J key"

  KEY_K:
    type: KEY_K
    range: [0, 2]
    description: "K key"

  KEY_L:
    type: KEY_L
    range: [0, 2]
    description: "L key"

  KEY_SEMICOLON:
    type: KEY_SEMICOLON
    range: [0, 2]
    description: "Semicolon key"

  KEY_APOSTROPHE:
    type: KEY_APOSTROPHE
    range: [0, 2]
    description: "Apostrophe/Quote key"

  KEY_GRAVE:
    type: KEY_GRAVE
    range: [0, 2]
    description: "Grave/Tilde key"

  KEY_LEFTSHIFT:
    type: KEY_LEFTSHIFT
    range: [0, 2]
    description: "Left Shift modifier key"

  KEY_BACKSLASH:
    type: KEY_BACKSLASH
    range: [0, 2]
    description: "Backslash/Pipe key"

  KEY_Z:
    type: KEY_Z
    range: [0, 2]
    description: "Z key"

  KEY_X:
    type: KEY_X
    range: [0, 2]
    description: "X key"

  KEY_C:
    type: KEY_C
    range: [0, 2]
    description: "C key"

  KEY_V:
    type: KEY_V
    range: [0, 2]
    description: "V key"

  KEY_B:
    type: KEY_B
    range: [0, 2]
    description: "B key"

  KEY_N:
    type: KEY_N
    range: [0, 2]
    description: "N key"

  KEY_M:
    type: KEY_M
    range: [0, 2]
    description: "M key"

  KEY_COMMA:
    type: KEY_COMMA
    range: [0, 2]
    description: "Comma/Less-than key"

  KEY_DOT:
    type: KEY_DOT
    range: [0, 2]
    description: "Period/Greater-than key"

  KEY_SLASH:
    type: KEY_SLASH
    range: [0, 2]
    description: "Slash/Question-mark key"

  KEY_RIGHTSHIFT:
    type: KEY_RIGHTSHIFT
    range: [0, 2]
    description: "Right Shift modifier key"

  KEY_SPACE:
    type: KEY_SPACE
    range: [0, 2]
    description: "Spacebar"

  KEY_CAPSLOCK:
    type: KEY_CAPSLOCK
    range: [0, 2]
    description: "Caps Lock toggle key"

  # --- Function Keys ---
  KEY_F1:
    type: KEY_F1
    range: [0, 2]
    description: "Function key F1"

  KEY_F2:
    type: KEY_F2
    range: [0, 2]
    description: "Function key F2"

  KEY_F3:
    type: KEY_F3
    range: [0, 2]
    description: "Function key F3"

  KEY_F4:
    type: KEY_F4
    range: [0, 2]
    description: "Function key F4"

  KEY_F5:
    type: KEY_F5
    range: [0, 2]
    description: "Function key F5"

  KEY_F6:
    type: KEY_F6
    range: [0, 2]
    description: "Function key F6"

  KEY_F7:
    type: KEY_F7
    range: [0, 2]
    description: "Function key F7"

  KEY_F8:
    type: KEY_F8
    range: [0, 2]
    description: "Function key F8"

  KEY_F9:
    type: KEY_F9
    range: [0, 2]
    description: "Function key F9"

  KEY_F10:
    type: KEY_F10
    range: [0, 2]
    description: "Function key F10"

  KEY_F11:
    type: KEY_F11
    range: [0, 2]
    description: "Function key F11"

  KEY_F12:
    type: KEY_F12
    range: [0, 2]
    description: "Function key F12"

  KEY_F13:
    type: KEY_F13
    range: [0, 2]
    description: "Function key F13"

  KEY_F14:
    type: KEY_F14
    range: [0, 2]
    description: "Function key F14"

  KEY_F15:
    type: KEY_F15
    range: [0, 2]
    description: "Function key F15"

  KEY_F16:
    type: KEY_F16
    range: [0, 2]
    description: "Function key F16"

  KEY_F17:
    type: KEY_F17
    range: [0, 2]
    description: "Function key F17"

  KEY_F18:
    type: KEY_F18
    range: [0, 2]
    description: "Function key F18"

  KEY_F19:
    type: KEY_F19
    range: [0, 2]
    description: "Function key F19"

  KEY_F20:
    type: KEY_F20
    range: [0, 2]
    description: "Function key F20"

  KEY_F21:
    type: KEY_F21
    range: [0, 2]
    description: "Function key F21"

  KEY_F22:
    type: KEY_F22
    range: [0, 2]
    description: "Function key F22"

  KEY_F23:
    type: KEY_F23
    range: [0, 2]
    description: "Function key F23"

  KEY_F24:
    type: KEY_F24
    range: [0, 2]
    description: "Function key F24"

  # --- Navigation & Editing Keys ---
  KEY_PRINT:
    type: KEY_PRINT
    range: [0, 2]
    description: "Print Screen key"

  KEY_SCROLLLOCK:
    type: KEY_SCROLLLOCK
    range: [0, 2]
    description: "Scroll Lock toggle key"

  KEY_PAUSE:
    type: KEY_PAUSE
    range: [0, 2]
    description: "Pause/Break key"

  KEY_INSERT:
    type: KEY_INSERT
    range: [0, 2]
    description: "Insert key"

  KEY_HOME:
    type: KEY_HOME
    range: [0, 2]
    description: "Home key"

  KEY_PAGEUP:
    type: KEY_PAGEUP
    range: [0, 2]
    description: "Page Up key"

  KEY_DELETE:
    type: KEY_DELETE
    range: [0, 2]
    description: "Delete key"

  KEY_END:
    type: KEY_END
    range: [0, 2]
    description: "End key"

  KEY_PAGEDOWN:
    type: KEY_PAGEDOWN
    range: [0, 2]
    description: "Page Down key"

  KEY_RIGHT:
    type: KEY_RIGHT
    range: [0, 2]
    description: "Right arrow key"

  KEY_LEFT:
    type: KEY_LEFT
    range: [0, 2]
    description: "Left arrow key"

  KEY_DOWN:
    type: KEY_DOWN
    range: [0, 2]
    description: "Down arrow key"

  KEY_UP:
    type: KEY_UP
    range: [0, 2]
    description: "Up arrow key"

  # --- Keypad Keys ---
  KEY_NUMLOCK:
    type: KEY_NUMLOCK
    range: [0, 2]
    description: "Num Lock toggle key"

  KEY_KPSLASH:
    type: KEY_KPSLASH
    range: [0, 2]
    description: "Keypad divide key"

  KEY_KPASTERISK:
    type: KEY_KPASTERISK
    range: [0, 2]
    description: "Keypad multiply key"

  KEY_KPMINUS:
    type: KEY_KPMINUS
    range: [0, 2]
    description: "Keypad subtract key"

  KEY_KP7:
    type: KEY_KP7
    range: [0, 2]
    description: "Keypad 7 key"

  KEY_KP8:
    type: KEY_KP8
    range: [0, 2]
    description: "Keypad 8 key"

  KEY_KP9:
    type: KEY_KP9
    range: [0, 2]
    description: "Keypad 9 key"

  KEY_KPPLUS:
    type: KEY_KPPLUS
    range: [0, 2]
    description: "Keypad add key"

  KEY_KP4:
    type: KEY_KP4
    range: [0, 2]
    description: "Keypad 4 key"

  KEY_KP5:
    type: KEY_KP5
    range: [0, 2]
    description: "Keypad 5 key"

  KEY_KP6:
    type: KEY_KP6
    range: [0, 2]
    description: "Keypad 6 key"

  KEY_KP1:
    type: KEY_KP1
    range: [0, 2]
    description: "Keypad 1 key"

  KEY_KP2:
    type: KEY_KP2
    range: [0, 2]
    description: "Keypad 2 key"

  KEY_KP3:
    type: KEY_KP3
    range: [0, 2]
    description: "Keypad 3 key"

  KEY_KP0:
    type: KEY_KP0
    range: [0, 2]
    description: "Keypad 0 key"

  KEY_KPDOT:
    type: KEY_KPDOT
    range: [0, 2]
    description: "Keypad decimal point key"

  KEY_KPENTER:
    type: KEY_KPENTER
    range: [0, 2]
    description: "Keypad Enter key"

  KEY_KPEQUAL:
    type: KEY_KPEQUAL
    range: [0, 2]
    description: "Keypad equals key"

  # --- Modifier Keys ---
  KEY_RIGHTCTRL:
    type: KEY_RIGHTCTRL
    range: [0, 2]
    description: "Right Control modifier key"

  KEY_RIGHTALT:
    type: KEY_RIGHTALT
    range: [0, 2]
    description: "Right Alt/AltGr modifier key"

  KEY_LEFTMETA:
    type: KEY_LEFTMETA
    range: [0, 2]
    description: "Left Meta/Windows/Super key"

  KEY_RIGHTMETA:
    type: KEY_RIGHTMETA
    range: [0, 2]
    description: "Right Meta/Windows/Super key"

  KEY_COMPOSE:
    type: KEY_COMPOSE
    range: [0, 2]
    description: "Compose key for special characters"

  # --- System & Multimedia Keys ---
  KEY_POWER:
    type: KEY_POWER
    range: [0, 2]
    description: "Power button"

  KEY_SLEEP:
    type: KEY_SLEEP
    range: [0, 2]
    description: "Sleep/Suspend button"

  KEY_WAKEUP:
    type: KEY_WAKEUP
    range: [0, 2]
    description: "Wake-up event button"

  KEY_MUTE:
    type: KEY_MUTE
    range: [0, 2]
    description: "Audio mute toggle"

  KEY_VOLUMEDOWN:
    type: KEY_VOLUMEDOWN
    range: [0, 2]
    description: "Volume decrease button"

  KEY_VOLUMEUP:
    type: KEY_VOLUMEUP
    range: [0, 2]
    description: "Volume increase button"

  KEY_NEXTSONG:
    type: KEY_NEXTSONG
    range: [0, 2]
    description: "Next track button"

  KEY_PREVIOUSSONG:
    type: KEY_PREVIOUSSONG
    range: [0, 2]
    description: "Previous track button"

  KEY_PLAYPAUSE:
    type: KEY_PLAYPAUSE
    range: [0, 2]
    description: "Play/Pause toggle button"

  KEY_STOPCD:
    type: KEY_STOPCD
    range: [0, 2]
    description: "Stop media playback button"

  KEY_HOMEPAGE:
    type: KEY_HOMEPAGE
    range: [0, 2]
    description: "Open homepage/browser button"

  KEY_MAIL:
    type: KEY_MAIL
    range: [0, 2]
    description: "Open email client button"

  KEY_SEARCH:
    type: KEY_SEARCH
    range: [0, 2]
    description: "Search button"

  KEY_BACK:
    type: KEY_BACK
    range: [0, 2]
    description: "Browser back button"

  KEY_FORWARD:
    type: KEY_FORWARD
    range: [0, 2]
    description: "Browser forward button"

  KEY_EJECTCD:
    type: KEY_EJECTCD
    range: [0, 2]
    description: "Eject CD/DVD button"

    # --- Miscellaneous Keys ---
  KEY_SYSRQ:
    type: KEY_SYSRQ
    range: [0, 2]
    description: "System Request/Print Screen key"

  KEY_MENU:
    type: KEY_MENU
    range: [0, 2]
    description: "Context menu key"

"#.into();

    #[cfg(feature = "midi")]
    {
        s += r#" 

#############################################################################
#    
# ----------------
# MIDI Controls
# ----------------
midi_controls:
  FILTER_RESPONSE:
    midi_message:
      type: control_change
      channel: any
      number: 71
    range: [0, 127]
    description: "Filter response (CC71)"

  RELEASE_TIME:
    midi_message:
      type: control_change
      channel: any
      number: 72
    range: [0, 127]
    description: "Release time (CC72)"

  ATTACK_TIME:
    midi_message:
      type: control_change
      channel: any
      number: 73
    range: [0, 127]
    description: "Attack time (CC73)"

  FILTER_CUTOFF:
    midi_message:
      type: control_change
      channel: any
      number: 74
    range: [0, 127]
    description: "Filter cutoff (CC74)"

  DECAY_TIME:
    midi_message:
      type: control_change
      channel: any
      number: 75
    range: [0, 127]
    description: "Decay time (CC75)"
    
  SUSTAIN_PEDAL:
    midi_message:
      type: control_change
      channel: any
      number: 64
    range: [0, 127]
    description: "Sustain pedal (CC64)"

  PORTAMENTO_PEDAL:
    midi_message:
      type: control_change
      channel: any
      number: 65
    range: [0, 127]
    description: "Portamento (CC65)"

  SUSTENUDO_PEDAL:
    midi_message:
      type: control_change
      channel: any
      number: 66
    range: [0, 127]
    description: "Sostenudo (CC66)"

  SOFT_PEDAL:
    midi_message:
      type: control_change
      channel: any
      number: 67
    range: [0, 127]
    description: "Soft (CC67)"

  BREATH:
    midi_message:
      type: control_change
      channel: any
      number: 2
    range: [0, 127]
    description: "Breath Controller (CC2)"

  PITCH_WHEEL:
    midi_message:
      type: pitch_wheel
      channel: any
    range: [-8192, 8191]
    description: "Pitch bend wheel"

  MODULATION_WHEEL:
    midi_message:
      type: control_change
      channel: any
      number: 1
    range: [0, 127]
    description: "Modulation wheel (CC1)"

  EXPRESSION_PEDAL:
    midi_message:
      type: control_change
      channel: any
      number: 11
    range: [0, 127]
    description: "Expression pedal (CC11)"

  VOLUME:
    midi_message:
      type: control_change
      channel: any
      number: 7
    range: [0, 127]
    description: "Main volume (CC7)"

  PAN:
    midi_message:
      type: control_change
      channel: any
      number: 10
    range: [0, 127]
    description: "Pan position (CC10)"

  AFTERTOUCH:
    midi_message:
      type: aftertouch
      channel: any
    range: [0, 127]
    description: "Channel aftertouch"

  # Note definitions - all chromatic notes (all octaves)
  NOTE_C:
    midi_message:
      type: note
      channel: any
      number: [0, 12, 24, 36, 48, 60, 72, 84, 96, 108, 120]
    range: [0, 127]
    description: "Note C (all octaves)"

  NOTE_C#:
    midi_message:
      type: note
      channel: any
      number: [1, 13, 25, 37, 49, 61, 73, 85, 97, 109, 121]
    range: [0, 127]
    description: "Note C# (all octaves)"

  NOTE_D:
    midi_message:
      type: note
      channel: any
      number: [2, 14, 26, 38, 50, 62, 74, 86, 98, 110, 122]
    range: [0, 127]
    description: "Note D (all octaves)"

  NOTE_D#:
    midi_message:
      type: note
      channel: any
      number: [3, 15, 27, 39, 51, 63, 75, 87, 99, 111, 123]
    range: [0, 127]
    description: "Note D# (all octaves)"

  NOTE_E:
    midi_message:
      type: note
      channel: any
      number: [4, 16, 28, 40, 52, 64, 76, 88, 100, 112, 124]
    range: [0, 127]
    description: "Note E (all octaves)"

  NOTE_F:
    midi_message:
      type: note
      channel: any
      number: [5, 17, 29, 41, 53, 65, 77, 89, 101, 113, 125]
    range: [0, 127]
    description: "Note F (all octaves)"

  NOTE_F#:
    midi_message:
      type: note
      channel: any
      number: [6, 18, 30, 42, 54, 66, 78, 90, 102, 114, 126]
    range: [0, 127]
    description: "Note F# (all octaves)"

  NOTE_G:
    midi_message:
      type: note
      channel: any
      number: [7, 19, 31, 43, 55, 67, 79, 91, 103, 115, 127]
    range: [0, 127]
    description: "Note G (all octaves)"

  NOTE_G#:
    midi_message:
      type: note
      channel: any
      number: [8, 20, 32, 44, 56, 68, 80, 92, 104, 116]
    range: [0, 127]
    description: "Note G# (all octaves)"

  NOTE_A:
    midi_message:
      type: note
      channel: any
      number: [9, 21, 33, 45, 57, 69, 81, 93, 105, 117]
    range: [0, 127]
    description: "Note A (all octaves)"

  NOTE_A#:
    midi_message:
      type: note
      channel: any
      number: [10, 22, 34, 46, 58, 70, 82, 94, 106, 118]
    range: [0, 127]
    description: "Note A# (all octaves)"

  NOTE_B:
    midi_message:
      type: note
      channel: any
      number: [11, 23, 35, 47, 59, 71, 83, 95, 107, 119]
    range: [0, 127]
    description: "Note B (all octaves)"
"#;
    }

    serde_saphyr::from_str(&s).expect("Failed to parse built-in predefined controls")
});
